[package]
name = "podanvil"
version = "0.9.1"
authors = ["Attila Toth <thaodean.gmail.com>"]
edition = "2018"

[[bin]]
name = "podanvil"
path = "src/main.rs"

[dependencies]
actix-web = "*"
actix-rt = "*"
actix-files = "*"
warp = "*" 
tokio = { version = "*", features = ["full"] }

