apiVersion: apps/v1
kind: Deployment
metadata:
  name: podanvil
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podanvil
  template:
    metadata:
      labels:
        app: podanvil
    spec:
      containers:
      - name: podanvil
        image: thaodean/podanvil:latest
        args: ["./thaodean.com"]
