apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thaodean-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: thaodean-com.podanvil.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: thaodean-service
            port:
              number: 80

